#!/bin/sh
cd ../
mysql -h $DRUPAL_SYNC_DB_HOST \
  -u $DRUPAL_SYNC_DB_USERNAME \
  -p$DRUPAL_SYNC_DB_PASSWORD \
  -e "DROP TABLE $DRUPAL_SYNC_DB_NAME"
cat $DRUPAL_DB_FILE | mysql -h $DRUPAL_SYNC_DB_HOST \
  -u $DRUPAL_SYNC_DB_USERNAME \
  -p$DRUPAL_SYNC_DB_PASSWORD \
  -D $DRUPAL_SYNC_DB_NAME
